name: Build and deploy Python app to Azure Web App - cqu-covidmap

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Build using AppService-Build
      uses: azure/appservice-build@v1
      with:
        platform: python
        platform-version: '3.7'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'cqu-covidmap'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_183da5c39913435aaedfbb91c7bceffb }}