name: Build and deploy Python app to Azure Web App - cqucovid

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Build using AppService-Build
      uses: azure/appservice-build@v1
      with:
        platform: python
        platform-version: '3.7'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'cqucovid'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3fd61ac0216346e4b695a67f8d945c2b }}
#        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}